[[redirects]]
  from = "/responsive/:width/:image"
  to = "https://res.cloudinary.com/nho/image/fetch/q_auto,f_auto,w_:width,c_limit/https://demo-11ty-netlify-cloudinary.netlify.app/:image"
  # status = 200